import { createRequire } from 'module'
const require = createRequire(import.meta.url)
const TelegramBot = require('node-telegram-bot-api');
const Canvas = require('canvas');
const fs = require('fs');

// Replace the value below with the Telegram token you receive from @BotFather
const token = '';

// Create a new bot instance
const bot = new TelegramBot(token, { polling: true });

//message count
let count = 0;
// 0: start 1: mode 2: first msg 3: second msg
let firstmessage = "";

const start = "/start"

// Listen for incoming messages
bot.on('message', (msg) => {
    // Load the meme image template from file
    const messageText = msg.text;

    if (messageText.localeCompare(start) == 0) {
        console.log("start");
        count = 1;
        bot.sendMessage(msg.chat.id, "Let's make a meme! Choose from the following billywait billyfbi");

    }
    else if (count == 1) {
        if (messageText.localeCompare("billywait") == 0) {
            console.log("===============Mode===============  ", messageText);
            const memeImage1 = new Canvas.Image();
            memeImage1.src = fs.readFileSync('./meme_template1.png');

            const canvas1 = Canvas.createCanvas(memeImage1.width, memeImage1.height);
            const ctx1 = canvas1.getContext('2d');

            // Draw the meme image onto the canvas
            ctx1.drawImage(memeImage1, 0, 0, memeImage1.width, memeImage1.height);

            bot.sendPhoto(msg.chat.id, canvas1.toBuffer('image/png'));

            // Delay for 1 seconds
            setTimeout(() => {
                bot.sendMessage(msg.chat.id, "Generating Billy...Wait! Please send what you'd like in the first text box");
            }, 1000)

            count = 2;
        }     

    }

    else if (count == 2) {
        firstmessage = messageText;
        console.log("===============First Message===============  ", firstmessage);
        bot.sendMessage(msg.chat.id, "Send me what you'd like for the second text box");
        count = 3;
    }
    else if (count == 3){

        const memeImage = new Canvas.Image();
        memeImage.src = fs.readFileSync('./meme_template.jpg');

        // Create an empty canvas to draw on using the same dimensions as the image template
        const canvas = Canvas.createCanvas(memeImage.width, memeImage.height);
        const ctx = canvas.getContext('2d');


        // Draw the meme image onto the canvas
        ctx.drawImage(memeImage, 0, 0, memeImage.width, memeImage.height);

        // Parse the text message sent by the user

        console.log("===============Second Message==============  ", messageText);

        // Define the font and color for the text
        ctx.font = '16px Arial';
        ctx.fillStyle = 'black';

        // Calculate the position of the text on the image
        const x1 = 210;
        const y1 = memeImage.height / 2 + 80;

        const x2 = memeImage.width / 2 + 100;
        const y2 = memeImage.height / 2 + 120;


        const lineHeight = 20;


        let words = firstmessage.split(' ');
        let line = '';
        let lines = [];
        for (let i = 0; i < words.length; i++) {
            let testLine = line + words[i] + ' ';
            let metrics = ctx.measureText(testLine);
            let testWidth = metrics.width;
            if (testWidth > 200 && i > 0) {
                lines.push(line);
                line = words[i] + ' ';
            }
            else {
                line = testLine;
            }
        }
        lines.push(line);

        // Write the text onto the canvas
        ctx.textAlign = 'center';
        for (let i = 0; i < lines.length && i * lineHeight < 100; i++) {
            ctx.fillText(lines[i], x1, y1 + i * lineHeight);
        }

        words = messageText.split(' ');
        line = '';
        lines = [];
        for (let i = 0; i < words.length; i++) {
            let testLine = line + words[i] + ' ';
            let metrics = ctx.measureText(testLine);
            let testWidth = metrics.width;
            if (testWidth > 100 && i > 0) {
                lines.push(line);
                line = words[i] + ' ';
            }
            else {
                line = testLine;
            }
        }
        lines.push(line);

        // Write the text onto the canvas
        ctx.textAlign = 'center';
        for (let i = 0; i < lines.length && i * lineHeight < 100; i++) {
            ctx.fillText(lines[i], x2, y2 + i * lineHeight);
        }


        // Get the modified image data as a Buffer
        const modifiedImageData = canvas.toBuffer('image/png');

        // Send the modified image back to the user
        bot.sendPhoto(msg.chat.id, modifiedImageData, { caption: `Generated by BillyMemeBot - @BillyOfficialERC` });

        count = 0;
    }

});


